#what is the goal of your workflows.
#Goal: whenever someone changes the python code,
# the linter will check if the syntax ,formmat, indentation(linting) is correct or not.

name: Auto Linter
on:
  push:
    paths: "*.py"
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout/clone code
        uses: actions/checkout@v7
        
      - name: Install linter
        run: pip install ruff
        
      - name: Check files for linting
        run: ruff check .
    
    
